# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('tratamiento', models.CharField(max_length=100, null=True)),
                ('observacion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('cod_enfermedad', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre_enfermedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre_medico', models.CharField(max_length=100, null=True)),
                ('apellido_medico', models.CharField(max_length=100, null=True)),
                ('cedula_medico', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('edad', models.IntegerField(default=1)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=6)),
                ('municipio', models.CharField(choices=[('CP', 'Cruz Paredes'), ('AAT', 'Alb.ArveloTorrealba'), ('BA', 'Barinas'), ('OT', 'Otro')], max_length=50)),
                ('parroquia', models.CharField(choices=[('BARR', 'Barrancas'), ('MASP', 'Masparrito'), ('SOCO', 'Socorro'), ('OTRo', 'Otro')], max_length=50)),
                ('urb', models.CharField(choices=[('12m', '12 de Marzo'), ('12m2', '12 de Marzo II'), ('12oc', '12 de Octubre'), ('2dic', '2 de Diciembre'), ('BelL', 'Beltran Lucena'), ('BnVen', 'Buena Ventura'), ('BnVis', 'Buena Vista'), ('ChiT', 'Chico Toro'), ('Ceib', 'La Ceiba'), ('Cont', 'Conticinio'), ('ElC', 'El Centro'), ('ElC2', 'El Centro 2'), ('Merc', 'El Mercadito'), ('ElNz', 'El Nazareno'), ('ElRe', 'El Retruque'), ('LasEs', 'Las Esmeraldas'), ('LaMan', 'La Manga'), ('LaTri', 'Las Trinitarias'), ('LiB', 'Libertador'), ('BarNue', 'Barrio Nuevo'), ('PueVi', 'Pueblo Viejo'), ('RoBet', 'Romulo Betancourt'), ('ValV', 'Valle Verde'), ('LosMa', 'Cacerio Los Mangos'), ('CAALe', 'Cacerio Campo Alegre'), ('CrzBlan', 'Cacerio Cruz Blanca'), ('Guay', 'Cacerio Las Guayabitas'), ('LosMe', 'Cacerio Los Mereyes'), ('Masp', 'Cacerio Masparro'), ('AgBl', 'Sector Aguas  Blancas'), ('Algarr', 'Sector Algarrobo'), ('Euca', 'Sector Eucalipto'), ('matMan', 'Sector Mata de Mango'), ('Melen', 'Sector Melenero'), ('SanRaf', 'San Rafael'), ('Soc', 'Sector Soco'), ('Tinaj', 'Sector Tinaja'), ('other', 'Otro')], max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_enfermedad', models.CharField(max_length=200, null=True)),
                ('plan', models.TextField(max_length=2100)),
                ('nombre_enfermedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='enfermedad_presente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico_tratante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Registro'),
        ),
    ]
