# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(default=1)),
                ('telefono', models.IntegerField(default=1)),
                ('edad', models.IntegerField(default=1)),
                ('sexo', models.CharField(max_length=6)),
                ('municipio', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('urb', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
