# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160508_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
