# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-11 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20170110_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='observacion',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
