# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20160508_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
