# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-11 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20170110_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
