# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_continent_country_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
