# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='municipio',
            field=models.CharField(choices=[('CP', 'Cruz Paredes'), ('AAT', 'Alb.ArveloTorrealba'), ('BA', 'Barinas')], max_length=50),
        ),
    ]
