# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20160613_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AlterField(
            model_name='registro',
            name='municipio',
            field=models.CharField(choices=[('CP', 'Cruz Paredes'), ('AAT', 'Alb.ArveloTorrealba'), ('BA', 'Barinas'), ('OT', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='parroquia',
            field=models.CharField(choices=[('BARR', 'Barrancas'), ('MASP', 'Masparrito'), ('SOCO', 'Socorro'), ('OTRo', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=6),
        ),
        migrations.AlterField(
            model_name='registro',
            name='urb',
            field=models.CharField(choices=[('12m', '12 de Marzo'), ('12oc', '12 de Octubre'), ('2dic', '2 de Diciembre'), ('BelL', 'Beltran Lucena'), ('BnVen', 'Buena Ventura'), ('BnVis', 'Buena Vista'), ('ChiT', 'Chico Toro'), ('Cont', 'Conticinio'), ('ElC', 'El Centro'), ('Merc', 'El Mercadito'), ('ElNz', 'El Nazareno'), ('ElRe', 'El Retruque'), ('LasEs', 'Las Esmeraldas'), ('LaMan', 'La Manga'), ('LaTri', 'Las Trinitarias'), ('LiB', 'Libertador'), ('BarNue', 'Barrio Nuevo'), ('PueVi', 'Pueblo Viejo'), ('RoBet', 'Romulo Betancourt'), ('ValV', 'Valle Verde'), ('LosMa', 'Cacerio Los Mangos'), ('CAALe', 'Cacerio Campo Alegre'), ('CrzBlan', 'Cacerio Cruz Blanca'), ('Guay', 'Cacerio Las Guayabitas'), ('LosMe', 'Cacerio Los Mereyes'), ('Masp', 'Cacerio Masparro'), ('AgBl', 'Sector Aguas  Blancas'), ('Algarr', 'Sector Algarrobo'), ('Euca', 'Sector Eucalipto'), ('matMan', 'Sector Mata de Mango'), ('Melen', 'Sector Melenero'), ('SanRaf', 'San Rafael'), ('Soc', 'Sector Soco'), ('Tinaj', 'Sector Tinaja'), ('other', 'Otro')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
