# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20160614_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AlterField(
            model_name='registro',
            name='cedula',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
