# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20160615_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cedula',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
