# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20170114_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(default=datetime.date(2017, 1, 19)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pac', to='registro.Registro'),
        ),
    ]
