# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20160615_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.CharField(max_length=100, null=True)),
                ('observacion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('cod_enfermedad', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('nombre_enfermedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre_medico', models.CharField(max_length=100, null=True)),
                ('apellido_medico', models.CharField(max_length=100, null=True)),
                ('cedula_medico', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='enfermedad_presente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico_tratante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Registro'),
        ),
    ]
