# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_auto_20160618_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='enfermedad_presente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico_tratante',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='registro',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
