# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20160618_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.CharField(max_length=100, null=True)),
                ('observacion', models.CharField(max_length=100, null=True)),
                ('enfermedad_presente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad')),
                ('medico_tratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Registro')),
            ],
        ),
    ]
