# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(),
        ),
    ]
