# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_auto_20161001_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
