# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_auto_20161227_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
