# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_auto_20161230_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfermedad', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=200)),
                ('cod_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad')),
            ],
        ),
    ]
