# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_remove_std_nombre_enfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='cod_enfermedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Enfermedad'),
        ),
    ]
