# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_auto_20170109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='plan',
            field=models.TextField(max_length=2000),
        ),
    ]
